# Generated by Django 4.1.1 on 2023-05-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0002_remove_carteditem_price_remove_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteditem',
            old_name='Price',
            new_name='price',
        ),
    ]
