# Generated by Django 4.1.1 on 2023-05-18 11:21

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0003_auto_20230518_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orderID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
