# Generated by Django 4.1.1 on 2023-05-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0004_auto_20230518_2321'),
        ('kiwinco', '0004_item_pricefloat'),
    ]

    operations = [
    ]
