# Generated by Django 4.1.1 on 2023-06-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0005_merge_0004_auto_20230518_2321_0004_item_pricefloat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('is_authenticated', models.BooleanField(default=False)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('access_key', models.CharField(max_length=100)),
                ('refresh_key', models.CharField(max_length=100)),
            ],
        ),
    ]
