# Generated by Django 4.1.1 on 2023-06-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0006_currentuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentuser',
            old_name='access_key',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='currentuser',
            old_name='refresh_key',
            new_name='refresh_token',
        ),
    ]
