# Generated by Django 4.1.1 on 2023-06-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwinco', '0007_rename_access_key_currentuser_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
